/**
 * Tailwind adapter (PLAN §8, stack tailwind). Tailwind REUSES the css-vars
 * `tokens.css` (the `:root` / `[data-theme]` blocks) for mode-scoped values, and
 * adds a preset that maps SEMANTIC token names to those CSS vars. Result:
 * utilities like `bg-bg-default` / `text-action-primary-fg` are mode-aware with
 * no per-mode Tailwind config — mode switching stays the shared data-theme JS.
 */

import { ThemeDefinition } from "../../tokens/types.js";
import { flattenTokens } from "../../tokens/resolver.js";
import { cssVarRef } from "../css-vars/naming.js";
import { googleFontsLinks } from "../css-vars/emit.js";
import { getComponentSpec, listComponentNames } from "../../components/specs.js";

type Nested = { [k: string]: string | Nested };

/** Build a nested object of var() refs for tokens under `prefix`. */
function nestUnder(theme: ThemeDefinition, prefix: string, opts?: { skipSecond?: string[] }): Nested {
  const root: Nested = {};
  for (const [path, node] of flattenTokens(theme.tokens)) {
    if (path !== prefix && !path.startsWith(prefix + ".")) continue;
    if (node.$type === "typography") continue;
    const rest = path.slice(prefix.length + 1).split(".").filter(Boolean);
    if (rest.length === 0) continue;
    // Exclude primitive sub-groups (e.g. color.blue) so raw palette utilities
    // like `bg-blue-500` are NOT made valid — that's what no-raw-class forbids.
    if (opts?.skipSecond?.includes(rest[0])) continue;
    let cur = root;
    for (let i = 0; i < rest.length - 1; i++) {
      cur[rest[i]] ??= {};
      cur = cur[rest[i]] as Nested;
    }
    cur[rest[rest.length - 1]] = cssVarRef(path);
  }
  return root;
}

/** Emit a Tailwind preset (CommonJS) wiring semantic tokens to CSS vars. */
export function emitTailwindPreset(theme: ThemeDefinition): string {
  const preset = {
    // darkMode handled via data-theme + tokens.css; no Tailwind darkMode needed.
    theme: {
      extend: {
        // Only SEMANTIC colors (bg/text/border/action); primitives are excluded.
        colors: nestUnder(theme, "color", {
          skipSecond: ["white", "black", "gray", "blue", "red", "green", "amber"],
        }),
        borderRadius: nestUnder(theme, "radius"),
        boxShadow: nestUnder(theme, "elevation"),
        spacing: nestUnder(theme, "space"),
        // Typeface axis: `font-sans`/`font-mono` follow the [data-type] vars,
        // so the type switcher repaints Tailwind UIs the same way modes do.
        fontFamily: {
          sans: ["var(--font-family-sans)"],
          mono: ["var(--font-family-mono)"],
        },
      },
    },
  };
  return (
    "/* Generated by dsmcp — Tailwind preset mapping semantic tokens to CSS vars.\n" +
    " * Mode-aware via theme/tokens.css ([data-theme]); switch modes with theme/theme.js. */\n" +
    "module.exports = " +
    JSON.stringify(preset, null, 2) +
    ";\n"
  );
}

/** A starter tailwind.config.js that loads the preset. */
export function emitTailwindConfig(): string {
  return `/* Generated by dsmcp. */
module.exports = {
  presets: [require("./tailwind.preset.js")],
  content: ["./index.html", "./src/**/*.{html,js,jsx,ts,tsx,vue,svelte}"],
};
`;
}

/** Governed Tailwind component class strings, as a copy-ready markdown doc. */
export function emitTailwindComponentsDoc(): string {
  const parts = ["# Governed components (Tailwind)\n", "Copy these class strings — they use semantic preset utilities only.\n"];
  for (const name of listComponentNames()) {
    const res = getComponentSpec(name, "tailwind");
    if (res.ok && res.spec.code.tailwind) {
      parts.push(`## ${name}\n\n\`\`\`html\n${res.spec.code.tailwind}\n\`\`\``);
    }
  }
  return parts.join("\n") + "\n";
}

/** Starter index.html using governed Tailwind class strings (passes the rules). */
export function emitTailwindStarter(modes: string[], theme: ThemeDefinition): string {
  const btn = getComponentSpec("button", "tailwind");
  const buttons = btn.ok ? btn.spec.code.tailwind ?? "" : "";
  const fonts = googleFontsLinks(theme);
  const hasType = !!(theme.typeThemes && theme.typeThemes.length);
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>App (dsmcp Tailwind)</title>
${fonts}
  <!-- tokens.css provides the mode-scoped + typeface CSS vars the preset maps to. -->
  <link rel="stylesheet" href="./theme/tokens.css" />
  <!-- Build your Tailwind CSS with tailwind.config.js (presets it), then link it here. -->
  <link rel="stylesheet" href="./dist/tailwind.css" />
  <script src="./theme/theme.js"></script>
</head>
<body class="bg-bg-default text-text-primary font-sans">
  <div class="p-4 flex justify-end gap-4"><span id="dsmcp-theme-switcher"></span>${hasType ? `<span id="dsmcp-type-switcher"></span>` : ""}</div>
  <main class="max-w-2xl mx-auto p-8">
    <h1>Themed app</h1>
    <p>Modes: ${modes.join(", ")}${hasType ? ` · Typefaces: ${theme.typeThemes!.map((t) => t.name).join(", ")}` : ""}. Use semantic utilities; never raw palette utilities.</p>
    <div class="bg-bg-raised text-text-primary border border-border-default rounded-surface shadow-card p-6">
${buttons.replace(/^/gm, "      ")}
    </div>
  </main>
</body>
</html>
`;
}
