/**
 * Adoption artifacts (PLAN §8, §7) — the bridge from "tool exists" to "tool is
 * used": agent rules, project config, and enforcement wiring (pre-commit /
 * GitHub Action / Claude Code Stop-hook).
 *
 * IMPORTANT: `dsmcp validate` is a Phase-3 stub that exits 2 (not implemented).
 * Every generated enforcement script therefore treats exit code 2 as a pass and
 * prints a notice — so adopting the scaffold never blocks commits/CI before the
 * validator exists. Enforcement activates automatically once Phase 3 makes
 * `validate` return 0/1.
 */

import { ModeName, Stack } from "../tokens/types.js";
import { GeneratedFile } from "../util/files.js";

export interface ArtifactOptions {
  stack: Stack;
  modes: ModeName[];
  defaultMode: ModeName;
  /** dsmcp invocation used in generated scripts. */
  invoke?: string;
}

/** Shared guard: tolerate the Phase-3 not-implemented exit code (2). */
function guardedValidate(invoke: string): string {
  return [
    `${invoke} validate .`,
    `code=$?`,
    `if [ "$code" = "2" ]; then`,
    `  echo "[dsmcp] validate is a Phase-3 stub — skipping enforcement for now."`,
    `  exit 0`,
    `fi`,
    `exit $code`,
  ].join("\n");
}

export function buildArtifacts(opts: ArtifactOptions): GeneratedFile[] {
  const invoke = opts.invoke ?? "npx --yes dsmcp";
  const modesList = opts.modes.join(", ");

  const config = {
    $schema: "https://dsmcp.dev/schema/theme-governance.config.json",
    stack: opts.stack,
    modes: opts.modes,
    defaultMode: opts.defaultMode,
    modeStrategy: 'data-theme="<mode>"',
    scope: ["color", "typography", "spacing", "radius", "elevation", "motion"],
    tokenOverrides: {},
    rules: { severityOverrides: {} },
  };

  const isFlutter = opts.stack === "flutter";
  const noHardcode = isFlutter
    ? "NEVER hardcode Color(0x…) or Colors.<name>; use Theme.of(context).colorScheme.* (the themed token)."
    : "NEVER hardcode colors (hex/rgb/hsl), nor raw spacing/radius/shadow literals when a token exists.";
  const modeStrategy = isFlutter
    ? `Switch modes via ThemeController.setMode("<mode>") (Map<String, ThemeData> appThemes).`
    : `Use a single mode strategy: \`data-theme="<mode>"\`.`;

  const claudeMd = `# Design System Governance (dsmcp)

This project is governed by **dsmcp**. Every session:

1. Call \`get_contract({ stack: "${opts.stack}" })\` BEFORE writing any UI code.
2. Use ONLY approved tokens (\`list_tokens\`, \`resolve_token\`). ${noHardcode}
3. For any component, call \`get_component_spec\` and copy the governed blueprint.
4. Every interactive element MUST define its states (hover / active / focus-visible /
   disabled) in EVERY mode. Declared modes: ${modesList} (default: ${opts.defaultMode}).
5. ${modeStrategy}
6. Before finishing, run \`${invoke} validate .\` and fix every \`error\`.
`;

  const cursorrules = `# dsmcp design-system governance
- Before writing UI: get_contract({ stack: "${opts.stack}" }).
- ${noHardcode}
- Copy get_component_spec blueprints; cover the required states in every mode (${modesList}).
- ${modeStrategy} Run "${invoke} validate ." before finishing.
`;

  const preCommit = `#!/bin/sh
# Generated by dsmcp — pre-commit theme governance gate.
${guardedValidate(invoke)}
`;

  const ghAction = `name: dsmcp theme governance
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Validate design-system compliance
        run: |
          ${guardedValidate(invoke).split("\n").join("\n          ")}
`;

  // Snippet (not a clobber of .claude/settings.json): paste into hooks.Stop.
  const stopHook = `// dsmcp — Claude Code Stop-hook snippet.
// Merge into .claude/settings.json under "hooks": runs the validator at the end
// of each turn; while validate is a Phase-3 stub (exit 2) it passes through.
{
  "hooks": {
    "Stop": [
      {
        "matcher": "",
        "hooks": [
          { "type": "command", "command": "${invoke} validate ." }
        ]
      }
    ]
  }
}
`;

  const themeFiles = isFlutter
    ? "- `lib/theme/app_theme.dart` — generated `Map<String, ThemeData>` per mode (// dsmcp:generated).\n" +
      "- `lib/theme/theme_controller.dart` — N-mode ChangeNotifier (setMode)."
    : "- `theme/tokens.css` — design tokens as CSS vars per mode (`:root` + `[data-theme]`).\n" +
      "- `theme/components.css` / preset — governed components.\n" +
      "- `theme/theme.js` — N-mode switcher (prefers-color-scheme + localStorage).";

  const readme = `# Theme governance (generated by dsmcp)

Files:
${themeFiles}
- \`CLAUDE.md\`, \`.cursorrules\` — agent rules.
- \`theme-governance.config.json\` — project config (modes, scope, overrides).
- \`.husky/pre-commit\`, \`.github/workflows/dsmcp.yml\`, \`dsmcp.stop-hook.json\` —
  enforcement wiring (\`${invoke} validate .\`).

Modes: ${modesList} (default: ${opts.defaultMode}).
`;

  return [
    { path: "theme-governance.config.json", content: JSON.stringify(config, null, 2) + "\n", preserveExisting: true },
    { path: "CLAUDE.md", content: claudeMd, preserveExisting: true },
    { path: ".cursorrules", content: cursorrules, preserveExisting: true },
    { path: ".husky/pre-commit", content: preCommit },
    { path: ".github/workflows/dsmcp.yml", content: ghAction },
    { path: "dsmcp.stop-hook.json", content: stopHook },
    { path: "THEME_README.md", content: readme },
  ];
}
