/**
 * Theme-switcher generator (PLAN §8): N-mode aware.
 *  - exactly 2 modes -> a toggle button,
 *  - >2 modes        -> a <select> dropdown,
 * with `prefers-color-scheme` detection for the initial mode and
 * localStorage persistence. One consistent strategy: `data-theme` on <html>.
 */

import { ModeName } from "../tokens/types.js";

export interface SwitcherOptions {
  modes: ModeName[];
  defaultMode: ModeName;
  /** localStorage key. */
  storageKey?: string;
  /** Optional TYPEFACE axis (font-packs) — adds a second, independent switcher. */
  typeThemes?: ModeName[];
  defaultTypeTheme?: ModeName;
}

export function emitSwitcherJs(opts: SwitcherOptions): string {
  const modeJs = emitModeSwitcherJs(opts);
  if (!opts.typeThemes || opts.typeThemes.length === 0) return modeJs;
  return modeJs + "\n" + emitTypeSwitcherJs(opts.typeThemes, opts.defaultTypeTheme ?? opts.typeThemes[0]);
}

function emitModeSwitcherJs(opts: SwitcherOptions): string {
  const { modes, defaultMode } = opts;
  const storageKey = opts.storageKey ?? "dsmcp-theme";
  const isToggle = modes.length === 2;
  // For prefers-color-scheme we map the OS "dark" preference to the first mode
  // whose name contains "dark", else the default.
  const darkMode = modes.find((m) => /dark/i.test(m)) ?? defaultMode;
  const lightMode = modes.find((m) => /light/i.test(m)) ?? defaultMode;

  return `/* Generated by dsmcp — N-mode theme switcher (${isToggle ? "toggle" : "dropdown"}). */
(function () {
  var MODES = ${JSON.stringify(modes)};
  var DEFAULT_MODE = ${JSON.stringify(defaultMode)};
  var STORAGE_KEY = ${JSON.stringify(storageKey)};
  var DARK_MODE = ${JSON.stringify(darkMode)};
  var LIGHT_MODE = ${JSON.stringify(lightMode)};

  function systemMode() {
    try {
      if (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) return DARK_MODE;
    } catch (e) {}
    return LIGHT_MODE;
  }

  function stored() {
    try {
      var v = localStorage.getItem(STORAGE_KEY);
      return MODES.indexOf(v) >= 0 ? v : null;
    } catch (e) { return null; }
  }

  function currentMode() {
    return stored() || systemMode() || DEFAULT_MODE;
  }

  function applyMode(mode) {
    if (MODES.indexOf(mode) < 0) mode = DEFAULT_MODE;
    document.documentElement.setAttribute("data-theme", mode);
    try { localStorage.setItem(STORAGE_KEY, mode); } catch (e) {}
    document.dispatchEvent(new CustomEvent("dsmcp:modechange", { detail: { mode: mode } }));
  }

  // Apply ASAP to avoid a flash of the wrong mode.
  applyMode(currentMode());

  function mountSwitcher() {
    var host = document.getElementById("dsmcp-theme-switcher");
    if (!host) return;
    host.innerHTML = "";
    ${isToggle ? renderToggle() : renderDropdown()}
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mountSwitcher);
  } else {
    mountSwitcher();
  }

  // Follow OS changes only while the user hasn't explicitly chosen.
  try {
    window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", function () {
      if (!stored()) applyMode(systemMode());
    });
  } catch (e) {}

  window.dsmcpTheme = { apply: applyMode, modes: MODES, current: currentMode };
})();
`;
}

function renderToggle(): string {
  return `var btn = document.createElement("button");
    btn.type = "button";
    btn.className = "dsmcp-switcher dsmcp-switcher--toggle";
    function label() { return document.documentElement.getAttribute("data-theme"); }
    btn.textContent = "Mode: " + label();
    btn.addEventListener("click", function () {
      var cur = document.documentElement.getAttribute("data-theme");
      var next = MODES[(MODES.indexOf(cur) + 1) % MODES.length];
      applyMode(next);
      btn.textContent = "Mode: " + next;
    });
    host.appendChild(btn);`;
}

function renderDropdown(): string {
  return `var sel = document.createElement("select");
    sel.className = "dsmcp-switcher dsmcp-switcher--dropdown";
    sel.setAttribute("aria-label", "Theme mode");
    MODES.forEach(function (m) {
      var opt = document.createElement("option");
      opt.value = m; opt.textContent = m;
      sel.appendChild(opt);
    });
    sel.value = document.documentElement.getAttribute("data-theme");
    sel.addEventListener("change", function () { applyMode(sel.value); });
    document.addEventListener("dsmcp:modechange", function (e) { sel.value = e.detail.mode; });
    host.appendChild(sel);`;
}

/**
 * TYPEFACE axis switcher — independent of the color-mode axis. Sets
 * `data-type="<pack>"` on <html> (the CSS [data-type] blocks repoint the
 * font-family vars), persists to localStorage, and mounts a <select> into
 * `#dsmcp-type-switcher`. The default pack is the :root baseline (no block).
 */
function emitTypeSwitcherJs(types: ModeName[], defaultType: ModeName): string {
  return `/* Generated by dsmcp — TYPEFACE (font-pack) switcher, independent of color mode. */
(function () {
  var TYPES = ${JSON.stringify(types)};
  var DEFAULT_TYPE = ${JSON.stringify(defaultType)};
  var STORAGE_KEY = "dsmcp-type";

  function stored() {
    try { var v = localStorage.getItem(STORAGE_KEY); return TYPES.indexOf(v) >= 0 ? v : null; }
    catch (e) { return null; }
  }

  function applyType(t) {
    if (TYPES.indexOf(t) < 0) t = DEFAULT_TYPE;
    document.documentElement.setAttribute("data-type", t);
    try { localStorage.setItem(STORAGE_KEY, t); } catch (e) {}
    document.dispatchEvent(new CustomEvent("dsmcp:typechange", { detail: { type: t } }));
  }

  // Apply ASAP to avoid a flash of the wrong typeface.
  applyType(stored() || DEFAULT_TYPE);

  function mountTypeSwitcher() {
    var host = document.getElementById("dsmcp-type-switcher");
    if (!host) return;
    host.innerHTML = "";
    var sel = document.createElement("select");
    sel.className = "dsmcp-switcher dsmcp-switcher--type";
    sel.setAttribute("aria-label", "Typeface");
    TYPES.forEach(function (t) {
      var opt = document.createElement("option");
      opt.value = t; opt.textContent = t;
      sel.appendChild(opt);
    });
    sel.value = document.documentElement.getAttribute("data-type") || DEFAULT_TYPE;
    sel.addEventListener("change", function () { applyType(sel.value); });
    document.addEventListener("dsmcp:typechange", function (e) { sel.value = e.detail.type; });
    host.appendChild(sel);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mountTypeSwitcher);
  } else {
    mountTypeSwitcher();
  }

  window.dsmcpType = { apply: applyType, types: TYPES, current: function () { return document.documentElement.getAttribute("data-type") || DEFAULT_TYPE; } };
})();
`;
}
