/* Generated by dsmcp — Tailwind preset mapping semantic tokens to CSS vars.
 * Mode-aware via theme/tokens.css ([data-theme]); switch modes with theme/theme.js. */
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "dim": {
          "bg": "var(--color-dim-bg)",
          "subtle": "var(--color-dim-subtle)",
          "raised": "var(--color-dim-raised)",
          "text": "var(--color-dim-text)",
          "text2": "var(--color-dim-text2)",
          "muted": "var(--color-dim-muted)",
          "accent": "var(--color-dim-accent)",
          "line": "var(--color-dim-line)",
          "line2": "var(--color-dim-line2)",
          "sec": "var(--color-dim-sec)",
          "danger": "var(--color-dim-danger)"
        },
        "sepia": {
          "bg": "var(--color-sepia-bg)",
          "subtle": "var(--color-sepia-subtle)",
          "raised": "var(--color-sepia-raised)",
          "text": "var(--color-sepia-text)",
          "text2": "var(--color-sepia-text2)",
          "muted": "var(--color-sepia-muted)",
          "accent": "var(--color-sepia-accent)",
          "line": "var(--color-sepia-line)",
          "line2": "var(--color-sepia-line2)",
          "sec": "var(--color-sepia-sec)",
          "danger": "var(--color-sepia-danger)"
        },
        "solarized": {
          "base03": "var(--color-solarized-base03)",
          "base02": "var(--color-solarized-base02)",
          "base01": "var(--color-solarized-base01)",
          "base00": "var(--color-solarized-base00)",
          "base0": "var(--color-solarized-base0)",
          "base1": "var(--color-solarized-base1)",
          "base2": "var(--color-solarized-base2)",
          "base3": "var(--color-solarized-base3)",
          "blue": "var(--color-solarized-blue)",
          "accent": "var(--color-solarized-accent)",
          "danger": "var(--color-solarized-danger)"
        },
        "nord": {
          "pn0": "var(--color-nord-pn0)",
          "pn1": "var(--color-nord-pn1)",
          "pn2": "var(--color-nord-pn2)",
          "pn3": "var(--color-nord-pn3)",
          "snow0": "var(--color-nord-snow0)",
          "snow2": "var(--color-nord-snow2)",
          "frost": "var(--color-nord-frost)",
          "muted": "var(--color-nord-muted)",
          "accent": "var(--color-nord-accent)",
          "line": "var(--color-nord-line)",
          "line2": "var(--color-nord-line2)",
          "sec": "var(--color-nord-sec)",
          "danger": "var(--color-nord-danger)"
        },
        "love": {
          "bg": "var(--color-love-bg)",
          "subtle": "var(--color-love-subtle)",
          "raised": "var(--color-love-raised)",
          "text": "var(--color-love-text)",
          "text2": "var(--color-love-text2)",
          "muted": "var(--color-love-muted)",
          "accent": "var(--color-love-accent)",
          "line": "var(--color-love-line)",
          "line2": "var(--color-love-line2)",
          "sec": "var(--color-love-sec)",
          "danger": "var(--color-love-danger)"
        },
        "future": {
          "bg": "var(--color-future-bg)",
          "subtle": "var(--color-future-subtle)",
          "raised": "var(--color-future-raised)",
          "text": "var(--color-future-text)",
          "text2": "var(--color-future-text2)",
          "muted": "var(--color-future-muted)",
          "accent": "var(--color-future-accent)",
          "line": "var(--color-future-line)",
          "line2": "var(--color-future-line2)",
          "sec": "var(--color-future-sec)",
          "danger": "var(--color-future-danger)"
        },
        "synthwave": {
          "bg": "var(--color-synthwave-bg)",
          "subtle": "var(--color-synthwave-subtle)",
          "raised": "var(--color-synthwave-raised)",
          "text": "var(--color-synthwave-text)",
          "text2": "var(--color-synthwave-text2)",
          "muted": "var(--color-synthwave-muted)",
          "accent": "var(--color-synthwave-accent)",
          "line": "var(--color-synthwave-line)",
          "line2": "var(--color-synthwave-line2)",
          "sec": "var(--color-synthwave-sec)",
          "danger": "var(--color-synthwave-danger)"
        },
        "sakura": {
          "bg": "var(--color-sakura-bg)",
          "subtle": "var(--color-sakura-subtle)",
          "raised": "var(--color-sakura-raised)",
          "text": "var(--color-sakura-text)",
          "text2": "var(--color-sakura-text2)",
          "muted": "var(--color-sakura-muted)",
          "accent": "var(--color-sakura-accent)",
          "line": "var(--color-sakura-line)",
          "line2": "var(--color-sakura-line2)",
          "sec": "var(--color-sakura-sec)",
          "danger": "var(--color-sakura-danger)"
        },
        "forest": {
          "bg": "var(--color-forest-bg)",
          "subtle": "var(--color-forest-subtle)",
          "raised": "var(--color-forest-raised)",
          "text": "var(--color-forest-text)",
          "text2": "var(--color-forest-text2)",
          "muted": "var(--color-forest-muted)",
          "accent": "var(--color-forest-accent)",
          "line": "var(--color-forest-line)",
          "line2": "var(--color-forest-line2)",
          "sec": "var(--color-forest-sec)",
          "danger": "var(--color-forest-danger)"
        },
        "ocean": {
          "bg": "var(--color-ocean-bg)",
          "subtle": "var(--color-ocean-subtle)",
          "raised": "var(--color-ocean-raised)",
          "text": "var(--color-ocean-text)",
          "text2": "var(--color-ocean-text2)",
          "muted": "var(--color-ocean-muted)",
          "accent": "var(--color-ocean-accent)",
          "line": "var(--color-ocean-line)",
          "line2": "var(--color-ocean-line2)",
          "sec": "var(--color-ocean-sec)",
          "danger": "var(--color-ocean-danger)"
        },
        "coffee": {
          "bg": "var(--color-coffee-bg)",
          "subtle": "var(--color-coffee-subtle)",
          "raised": "var(--color-coffee-raised)",
          "text": "var(--color-coffee-text)",
          "text2": "var(--color-coffee-text2)",
          "muted": "var(--color-coffee-muted)",
          "accent": "var(--color-coffee-accent)",
          "line": "var(--color-coffee-line)",
          "line2": "var(--color-coffee-line2)",
          "sec": "var(--color-coffee-sec)",
          "danger": "var(--color-coffee-danger)"
        },
        "aurora": {
          "bg": "var(--color-aurora-bg)",
          "subtle": "var(--color-aurora-subtle)",
          "raised": "var(--color-aurora-raised)",
          "text": "var(--color-aurora-text)",
          "text2": "var(--color-aurora-text2)",
          "muted": "var(--color-aurora-muted)",
          "accent": "var(--color-aurora-accent)",
          "line": "var(--color-aurora-line)",
          "line2": "var(--color-aurora-line2)",
          "sec": "var(--color-aurora-sec)",
          "danger": "var(--color-aurora-danger)"
        },
        "bg": {
          "default": "var(--color-bg-default)",
          "subtle": "var(--color-bg-subtle)",
          "raised": "var(--color-bg-raised)"
        },
        "text": {
          "primary": "var(--color-text-primary)",
          "secondary": "var(--color-text-secondary)",
          "muted": "var(--color-text-muted)",
          "inverse": "var(--color-text-inverse)"
        },
        "border": {
          "default": "var(--color-border-default)",
          "subtle": "var(--color-border-subtle)"
        },
        "action": {
          "primary": {
            "bg": "var(--color-action-primary-bg)",
            "fg": "var(--color-action-primary-fg)",
            "border": "var(--color-action-primary-border)",
            "hover": "var(--color-action-primary-hover)",
            "active": "var(--color-action-primary-active)",
            "disabled": "var(--color-action-primary-disabled)",
            "focus": "var(--color-action-primary-focus)"
          },
          "secondary": {
            "bg": "var(--color-action-secondary-bg)",
            "fg": "var(--color-action-secondary-fg)",
            "border": "var(--color-action-secondary-border)",
            "hover": "var(--color-action-secondary-hover)",
            "active": "var(--color-action-secondary-active)",
            "disabled": "var(--color-action-secondary-disabled)",
            "focus": "var(--color-action-secondary-focus)"
          },
          "danger": {
            "bg": "var(--color-action-danger-bg)",
            "fg": "var(--color-action-danger-fg)",
            "border": "var(--color-action-danger-border)",
            "hover": "var(--color-action-danger-hover)",
            "active": "var(--color-action-danger-active)",
            "disabled": "var(--color-action-danger-disabled)",
            "focus": "var(--color-action-danger-focus)"
          }
        }
      },
      "borderRadius": {
        "none": "var(--radius-none)",
        "sm": "var(--radius-sm)",
        "md": "var(--radius-md)",
        "lg": "var(--radius-lg)",
        "xl": "var(--radius-xl)",
        "full": "var(--radius-full)",
        "control": "var(--radius-control)",
        "surface": "var(--radius-surface)"
      },
      "boxShadow": {
        "card": "var(--elevation-card)",
        "popover": "var(--elevation-popover)",
        "modal": "var(--elevation-modal)"
      },
      "spacing": {
        "0": "var(--space-0)",
        "1": "var(--space-1)",
        "2": "var(--space-2)",
        "3": "var(--space-3)",
        "4": "var(--space-4)",
        "5": "var(--space-5)",
        "6": "var(--space-6)",
        "8": "var(--space-8)",
        "10": "var(--space-10)",
        "12": "var(--space-12)",
        "16": "var(--space-16)",
        "inset": {
          "sm": "var(--space-inset-sm)",
          "md": "var(--space-inset-md)",
          "lg": "var(--space-inset-lg)"
        }
      },
      "fontFamily": {
        "sans": [
          "var(--font-family-sans)"
        ],
        "mono": [
          "var(--font-family-mono)"
        ]
      }
    }
  }
};
