/* Generated by dsmcp — N-mode theme switcher (dropdown). */
(function () {
  var MODES = ["light","dark","dim","midnight","high-contrast-light","high-contrast-dark","sepia","solarized-light","solarized-dark","nord","love","future","synthwave","sakura","forest","ocean","coffee","aurora"];
  var DEFAULT_MODE = "light";
  var STORAGE_KEY = "dsmcp-theme";
  var DARK_MODE = "dark";
  var LIGHT_MODE = "light";

  function systemMode() {
    try {
      if (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) return DARK_MODE;
    } catch (e) {}
    return LIGHT_MODE;
  }

  function stored() {
    try {
      var v = localStorage.getItem(STORAGE_KEY);
      return MODES.indexOf(v) >= 0 ? v : null;
    } catch (e) { return null; }
  }

  function currentMode() {
    return stored() || systemMode() || DEFAULT_MODE;
  }

  function applyMode(mode) {
    if (MODES.indexOf(mode) < 0) mode = DEFAULT_MODE;
    document.documentElement.setAttribute("data-theme", mode);
    try { localStorage.setItem(STORAGE_KEY, mode); } catch (e) {}
    document.dispatchEvent(new CustomEvent("dsmcp:modechange", { detail: { mode: mode } }));
  }

  // Apply ASAP to avoid a flash of the wrong mode.
  applyMode(currentMode());

  function mountSwitcher() {
    var host = document.getElementById("dsmcp-theme-switcher");
    if (!host) return;
    host.innerHTML = "";
    var sel = document.createElement("select");
    sel.className = "dsmcp-switcher dsmcp-switcher--dropdown";
    sel.setAttribute("aria-label", "Theme mode");
    MODES.forEach(function (m) {
      var opt = document.createElement("option");
      opt.value = m; opt.textContent = m;
      sel.appendChild(opt);
    });
    sel.value = document.documentElement.getAttribute("data-theme");
    sel.addEventListener("change", function () { applyMode(sel.value); });
    document.addEventListener("dsmcp:modechange", function (e) { sel.value = e.detail.mode; });
    host.appendChild(sel);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mountSwitcher);
  } else {
    mountSwitcher();
  }

  // Follow OS changes only while the user hasn't explicitly chosen.
  try {
    window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", function () {
      if (!stored()) applyMode(systemMode());
    });
  } catch (e) {}

  window.dsmcpTheme = { apply: applyMode, modes: MODES, current: currentMode };
})();

/* Generated by dsmcp — TYPEFACE (font-pack) switcher, independent of color mode. */
(function () {
  var TYPES = ["system","serif","mono","rounded","humanist","slab"];
  var DEFAULT_TYPE = "system";
  var STORAGE_KEY = "dsmcp-type";

  function stored() {
    try { var v = localStorage.getItem(STORAGE_KEY); return TYPES.indexOf(v) >= 0 ? v : null; }
    catch (e) { return null; }
  }

  function applyType(t) {
    if (TYPES.indexOf(t) < 0) t = DEFAULT_TYPE;
    document.documentElement.setAttribute("data-type", t);
    try { localStorage.setItem(STORAGE_KEY, t); } catch (e) {}
    document.dispatchEvent(new CustomEvent("dsmcp:typechange", { detail: { type: t } }));
  }

  // Apply ASAP to avoid a flash of the wrong typeface.
  applyType(stored() || DEFAULT_TYPE);

  function mountTypeSwitcher() {
    var host = document.getElementById("dsmcp-type-switcher");
    if (!host) return;
    host.innerHTML = "";
    var sel = document.createElement("select");
    sel.className = "dsmcp-switcher dsmcp-switcher--type";
    sel.setAttribute("aria-label", "Typeface");
    TYPES.forEach(function (t) {
      var opt = document.createElement("option");
      opt.value = t; opt.textContent = t;
      sel.appendChild(opt);
    });
    sel.value = document.documentElement.getAttribute("data-type") || DEFAULT_TYPE;
    sel.addEventListener("change", function () { applyType(sel.value); });
    document.addEventListener("dsmcp:typechange", function (e) { sel.value = e.detail.type; });
    host.appendChild(sel);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mountTypeSwitcher);
  } else {
    mountTypeSwitcher();
  }

  window.dsmcpType = { apply: applyType, types: TYPES, current: function () { return document.documentElement.getAttribute("data-type") || DEFAULT_TYPE; } };
})();
