/**
 * CSS-vars emitter (PLAN §8). Turns a theme into mode-scoped CSS custom
 * properties: `:root` carries the default mode's *complete* set, and each
 * `[data-theme="<mode>"]` carries that mode's *complete* set (full-resolved,
 * not deltas — matches resolver semantics, robust to selector order).
 *
 * Only scalar leaves are emitted. Composite typography (`$type: typography`)
 * is skipped — nothing references it as a single var and `toCssValue` would
 * mangle the object; components use the primitive font vars directly.
 */

import { ModeName, ThemeDefinition } from "../../tokens/types.js";
import { createContext, flattenTokens, resolveToken, ResolverContext } from "../../tokens/resolver.js";
import { getComponentSpec, listComponentNames } from "../../components/specs.js";
import { cssVarName, toCssValue } from "./naming.js";

/** Scalar token paths -> resolved CSS value for a mode (skips typography). */
function modeVars(
  theme: ThemeDefinition,
  mode: ModeName,
  ctx: ResolverContext = createContext(theme)
): Array<[string, string]> {
  const flat = flattenTokens(theme.tokens);
  const out: Array<[string, string]> = [];
  for (const [path, node] of flat) {
    if (node.$type === "typography") continue;
    try {
      out.push([cssVarName(path), toCssValue(resolveToken(path, mode, ctx))]);
    } catch {
      // unresolved in this mode — skip; validateTheme/doctor surfaces it.
    }
  }
  return out;
}

function block(selector: string, vars: Array<[string, string]>): string {
  const body = vars.map(([name, value]) => `  ${name}: ${value};`).join("\n");
  return `${selector} {\n${body}\n}`;
}

/**
 * Emit the tokens stylesheet for the given modes.
 * @param modes subset of the theme's declared modes to emit (in order).
 * @param defaultMode mode bound to `:root` (must be in `modes`).
 */
export function emitCssVars(
  theme: ThemeDefinition,
  modes: ModeName[],
  defaultMode: ModeName
): string {
  const ctx = createContext(theme);
  const header =
    `/* Generated by dsmcp — design tokens as CSS custom properties.\n` +
    ` * Modes: ${modes.join(", ")} (default: ${defaultMode}). DO NOT EDIT BY HAND. */\n`;

  // ORDER IS LOAD-BEARING: `:root` and `[data-theme="x"]` have equal specificity
  // (0,1,0); a non-default mode wins only because `:root` is emitted FIRST and
  // source order breaks the tie. Do not reorder these blocks.
  const blocks: string[] = [block(":root", modeVars(theme, defaultMode, ctx))];
  for (const mode of modes) {
    blocks.push(block(`[data-theme="${mode}"]`, modeVars(theme, mode, ctx)));
  }
  return header + "\n" + blocks.join("\n\n") + "\n";
}

/** Concatenate the governed component CSS for a CSS-based stack. */
export function emitComponentCss(stack: "css-vars" | "vanilla" = "css-vars"): string {
  const parts: string[] = [`/* Generated by dsmcp — governed components for ${stack}. */\n`];
  for (const name of listComponentNames()) {
    const res = getComponentSpec(name, stack);
    if (res.ok && res.spec.code[stack]) {
      parts.push(`/* ===== ${name} ===== */\n${res.spec.code[stack]}`);
    }
  }
  return parts.join("\n\n") + "\n";
}

/**
 * Emit the TYPEFACE axis: one `[data-type="<pack>"]` block per non-default
 * type-theme, repointing only `--font-family-sans` / `--font-family-mono`.
 *
 * ORDER IS LOAD-BEARING: these blocks must be appended AFTER the mode blocks in
 * tokens.css. `[data-theme="x"]` and `[data-type="y"]` have equal specificity
 * (0,1,0); when an element carries both attributes, the font vars win only
 * because the type block comes later in source order.
 *
 * EVERY pack gets a block — including the default. The default merely mirrors the
 * `:root` font primitives, but emitting it explicitly PINS any subtree scoped to
 * `[data-type="<default>"]` (e.g. the demo's "system" specimen card) instead of
 * letting it inherit whatever the global selection happens to be.
 */
export function emitTypeThemeCss(theme: ThemeDefinition): string {
  const packs = theme.typeThemes ?? [];
  if (!packs.length) return "";
  const blocks = packs.map(
    (p) =>
      `[data-type="${p.name}"] {\n` +
      `  --font-family-sans: ${p.sans};\n` +
      `  --font-family-mono: ${p.mono};\n}`
  );
  if (!blocks.length) return "";
  const header =
    `\n/* Generated by dsmcp — TYPEFACE axis (font-packs), orthogonal to color\n` +
    ` * modes. Switch with [data-type] (theme.js). Appended after the mode blocks\n` +
    ` * so font vars win source-order when an element has both data-theme + data-type. */\n`;
  return header + "\n" + blocks.join("\n\n") + "\n";
}

/**
 * `<link>` tags loading every Google font referenced by the theme's type-packs.
 * Returns "" when no pack declares a `google` spec. Uses `display=swap` (no
 * invisible-text flash). Emit into the <head> of HTML that switches typefaces.
 */
export function googleFontsLinks(theme: ThemeDefinition): string {
  const specs = (theme.typeThemes ?? []).flatMap((p) => p.google ?? []);
  if (!specs.length) return "";
  const families = specs.map((s) => `family=${s}`).join("&");
  const href = `https://fonts.googleapis.com/css2?${families}&display=swap`;
  return (
    `  <link rel="preconnect" href="https://fonts.googleapis.com" />\n` +
    `  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n` +
    `  <link rel="stylesheet" href="${href}" />`
  );
}

/** All CSS var names referenced via `var(--x)` inside a CSS string. */
export function referencedVarNames(css: string): Set<string> {
  const out = new Set<string>();
  const re = /var\(\s*(--[a-zA-Z0-9-]+)\s*\)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css))) out.add(m[1]);
  return out;
}

/** Var names *defined* for a given mode (used by the coherence check). */
export function definedVarNames(theme: ThemeDefinition, mode: ModeName): Set<string> {
  return new Set(modeVars(theme, mode).map(([name]) => name));
}
